#!/usr/bin/env python3
"""Present-tense tests: does TODAY's generator emit what TODAY's schema accepts?

    python3 tests/test_current_fixtures.py

Deliberately separate from tests/test_script_schema.py. The two corpora test
different things and must not be merged:

    tests/fixtures/scripts/<type>/    historical (2026-01 .. 2026-04)
                                      -> backward compatibility
    tests/fixtures/scripts/current/   generated by the prompts at HEAD
                                      -> present-tense correctness

Regenerate the current tier with tests/regenerate_current_fixtures.py
(~$0.003, script generation only, no TTS).
"""

import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from script_schema import check_script  # noqa: E402

CURRENT = ROOT / "tests" / "fixtures" / "scripts" / "current"

TYPES = ("educational", "quiz", "true_false", "fill_blank", "pronunciation",
         "vocabulary")

# Which types the prompts ask for a 3-item array from, and under what key.
# All three are DEAD PAYLOAD: emitted by GPT, read by nothing. See
# docs/schema-prompt-mismatches.md M2.
DEAD_ARRAYS = {
    "quiz": "questions",
    "true_false": "statements",
    "fill_blank": "sentences",
}


def load(video_type):
    return json.loads(
        (CURRENT / f"{video_type}.json").read_text(encoding="utf-8"))


def test_all_six_types_are_present():
    found = {p.stem for p in CURRENT.glob("*.json")}
    assert found == set(TYPES)


@pytest.mark.parametrize("video_type", TYPES)
def test_current_output_validates(video_type):
    """The whole point of this tier. A failure here means the generator and
    the schema have drifted apart TODAY — not that some 2026-01 file is old."""
    _, errors, _ = check_script(
        load(video_type), video_type=video_type,
        source=f"tests/fixtures/scripts/current/{video_type}.json")
    assert errors == []


@pytest.mark.parametrize("video_type", TYPES)
def test_current_output_is_lint_clean(video_type):
    _, _, warnings = check_script(load(video_type), video_type=video_type)
    assert warnings == []


# ── M1 resolved ──────────────────────────────────────────────────────────

@pytest.mark.parametrize("video_type", TYPES)
def test_publishing_metadata_is_emitted_by_every_type(video_type):
    """M1. Historical fixtures lack video_title only because they predate
    commit 0a7535f (2026-03-24). All six types emit it today, so its absence
    is now a real defect rather than an age artifact. The schema still marks
    it Optional for the historical tier; this test is what pins the
    present-tense contract."""
    data = load(video_type)
    assert data.get("video_title"), "video_title missing or empty"
    assert data.get("video_description"), "video_description missing or empty"


# ── M2 resolved ──────────────────────────────────────────────────────────

@pytest.mark.parametrize("video_type,key", sorted(DEAD_ARRAYS.items()))
def test_dead_arrays_are_emitted_today(video_type, key):
    """M2. `statements` and `sentences` are absent from every historical
    fixture, which left open whether GPT ignores that part of the prompt.
    It does not — all three types emit 3 items today. So the payload is dead
    in the READER, not the writer: elements [1] and [2] are generated, billed
    and discarded, and a '3-question quiz' renders one question."""
    data = load(video_type)
    assert isinstance(data.get(key), list)
    assert len(data[key]) == 3


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
