#!/usr/bin/env python3
"""The publication ledger: the primary key of a published video.

    python3 -m pytest tests/test_publication_log.py

Before this, manager.upload() returned an upload_id and both call sites threw
it away. The only trace was a PRE-adaptation title in the artifact sidecar,
missing the `#Shorts` suffix adapt_for_platform adds — so it did not even
match the live video. Nothing in this repo could name a published video.

No network: the platform API is stubbed at the requests boundary.
"""

import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import publication_log as PL  # noqa: E402


@pytest.fixture
def ledger(tmp_path, monkeypatch):
    path = tmp_path / "ledger.jsonl"
    monkeypatch.setattr(PL, "LEDGER_PATH", path)
    return path


def _record(**over):
    args = dict(
        artifact="fabric_20260116_201133",
        video_path="/x/fabric.mp4",
        video_type="quiz",
        platform="youtube",
        upload_id="dQw4w9WgXcQ",
        url="https://youtube.com/shorts/dQw4w9WgXcQ",
        published_title="¿Qué significa 'fabric'? #Shorts",
        published_description="Body.\n\n#LearnEnglish #AprendeIngles",
        hashtags=["LearnEnglish", "AprendeIngles"],
    )
    args.update(over)
    return PL.record_publication(**args)


# ── the primary key ──────────────────────────────────────────────────

def test_upload_id_and_url_reach_disk(ledger):
    _record()
    rows = PL.read_ledger()

    assert len(rows) == 1
    assert rows[0]["upload_id"] == "dQw4w9WgXcQ"
    assert rows[0]["url"].endswith("dQw4w9WgXcQ")
    assert rows[0]["platform"] == "youtube"
    assert rows[0]["published_at"]


def test_the_record_joins_back_to_its_artifact(ledger):
    _record()
    _record(artifact="other_video", upload_id="ZZZ")

    found = PL.find_by_artifact("fabric_20260116_201133")

    assert len(found) == 1
    assert found[0]["upload_id"] == "dQw4w9WgXcQ"
    assert found[0]["video_path"] == "/x/fabric.mp4"


def test_lookup_by_upload_id(ledger):
    _record()

    assert PL.find_by_upload_id("dQw4w9WgXcQ")["artifact"] == "fabric_20260116_201133"
    assert PL.find_by_upload_id("nope") is None


# ── the two shape requirements ───────────────────────────────────────

def test_one_artifact_can_be_published_to_several_platforms(ledger):
    """One row per publication, not one field per artifact."""
    _record(platform="youtube", upload_id="yt1")
    _record(platform="tiktok", upload_id="tt1")
    _record(platform="instagram", upload_id="ig1")

    rows = PL.find_by_artifact("fabric_20260116_201133")

    assert {r["platform"] for r in rows} == {"youtube", "tiktok", "instagram"}
    assert {r["upload_id"] for r in rows} == {"yt1", "tt1", "ig1"}


def test_the_record_survives_a_re_render_of_the_artifact(ledger):
    """The sidecar is regenerated by the pipeline and MOVED by
    move_to_uploaded; the ledger lives outside the artifact tree, so a
    re-render cannot clobber a publication that already happened."""
    _record()
    assert PL.LEDGER_PATH.parent != Path("/x")      # not beside the video

    # simulate a re-render writing a fresh sidecar over the artifact
    rows_before = PL.read_ledger()
    _record(platform="tiktok", upload_id="tt2")     # later publication appends

    assert PL.read_ledger()[:1] == rows_before[:1], "history was rewritten"
    assert len(PL.read_ledger()) == 2


def test_the_ledger_is_append_only(ledger):
    for i in range(3):
        _record(upload_id=f"id{i}")

    lines = ledger.read_text(encoding="utf-8").strip().splitlines()

    assert len(lines) == 3
    assert [json.loads(x)["upload_id"] for x in lines] == ["id0", "id1", "id2"]


# ── post-adaptation strings ──────────────────────────────────────────

def test_the_recorded_title_is_what_was_actually_published(ledger):
    """The old record stored the PRE-adaptation title, so it was missing the
    `#Shorts` suffix and would not match the live video. That is the specific
    thing that made the join fail in the audit."""
    _record()

    assert PL.read_ledger()[0]["published_title"].endswith("#Shorts")


def test_the_recorded_description_includes_the_hashtag_block(ledger):
    _record()
    row = PL.read_ledger()[0]

    assert "#LearnEnglish" in row["published_description"]
    assert row["hashtags"] == ["LearnEnglish", "AprendeIngles"]


# ── failure is loud ──────────────────────────────────────────────────

def test_a_failed_write_raises_rather_than_returning_quietly(tmp_path, monkeypatch):
    """A video that is live but unrecorded is worse than a failed upload: the
    failure can be retried, the unrecorded success must be found by hand."""
    monkeypatch.setattr(PL, "LEDGER_PATH", tmp_path / "nope" / "ledger.jsonl")

    def boom(*a, **k):
        raise OSError("disk full")
    monkeypatch.setattr(PL.Path, "mkdir", boom)

    with pytest.raises(PL.PublicationRecordError, match="could not be written"):
        _record()


def test_the_raised_error_names_the_lost_id(tmp_path, monkeypatch):
    """The operator has to be able to recover the id from the message."""
    monkeypatch.setattr(PL, "LEDGER_PATH", tmp_path / "x" / "ledger.jsonl")
    monkeypatch.setattr(PL.Path, "mkdir",
                        lambda *a, **k: (_ for _ in ()).throw(OSError("ro")))

    with pytest.raises(PL.PublicationRecordError, match="dQw4w9WgXcQ"):
        _record()


# ── end to end through the real upload path ──────────────────────────

def test_upload_path_persists_the_id_returned_by_a_stubbed_api(ledger, monkeypatch, tmp_path):
    """Drives UploadManager.upload with the HTTP layer stubbed, and asserts
    the id the API returned is on disk afterwards and joins to the artifact."""
    import uploader as U

    # A real file: upload_all checks existence before dispatching, so a fake
    # path would short-circuit the very path under test.
    video = tmp_path / "fabric.mp4"
    video.write_bytes(b"\x00" * 1024)

    class FakeResponse:
        status_code = 200
        def raise_for_status(self): pass
        def json(self): return {"id": "STUB_VIDEO_ID_42"}

    monkeypatch.setattr(U, "_load_token", lambda p: {
        "access_token": "tok", "refresh_token": "r",
        "expires_at": 9_999_999_999})
    monkeypatch.setattr(U.requests, "post", lambda *a, **k: FakeResponse())
    monkeypatch.setattr(U.requests, "put", lambda *a, **k: FakeResponse())

    yt = U.YouTubeUploader()
    monkeypatch.setattr(yt, "is_configured", lambda: True)
    monkeypatch.setattr(yt, "authenticate", lambda: True)
    monkeypatch.setattr(
        yt, "upload_video",
        lambda *a, **k: U.UploadResult("youtube", True,
                                       upload_id="STUB_VIDEO_ID_42",
                                       url="https://youtu.be/STUB_VIDEO_ID_42"))

    manager = U.UploadManager()
    manager.uploaders["youtube"] = yt
    result = manager.upload("youtube", str(video),
                            title="T #Shorts", description="D", hashtags=["a"])

    assert result["upload_id"] == "STUB_VIDEO_ID_42"

    PL.record_publication(
        artifact="fabric_20260116_201133", video_path=str(video),
        video_type="quiz", platform="youtube",
        upload_id=result["upload_id"], url=result["url"],
        published_title="T #Shorts", published_description="D", hashtags=["a"])

    on_disk = PL.find_by_artifact("fabric_20260116_201133")
    assert len(on_disk) == 1
    assert on_disk[0]["upload_id"] == "STUB_VIDEO_ID_42"
    assert on_disk[0]["video_path"] == str(video)


def test_both_admin_upload_paths_record(monkeypatch):
    """AST guard: every manager.upload() success branch must record."""
    import ast
    src = (ROOT / "src" / "admin.py").read_text(encoding="utf-8")

    assert src.count("_record_upload(") >= 3, (
        "expected the helper definition plus both upload call sites")
    tree = ast.parse(src)
    uploads = [n for n in ast.walk(tree)
               if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute)
               and n.func.attr == "upload"
               and isinstance(n.func.value, ast.Name)
               and n.func.value.id == "manager"]
    assert len(uploads) == 2, f"expected 2 manager.upload call sites, found {len(uploads)}"


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
