"""Character renderer with lip-sync animation.

Renders an animated character (e.g. turtle) onto video frames with
mouth movement synced to word-level timestamps from Whisper.
"""

import logging
import math
import os
from typing import Dict, List, Optional, Tuple

import yaml
from PIL import Image

logger = logging.getLogger(__name__)

# Config file path — resolve via __file__ so it works regardless of cwd
CONFIG_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "config.yaml",
)

# Project root for asset resolution
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mouth state names (order matters for oscillation indexing)
MOUTH_STATES = ["closed", "slightly_open", "open", "wide", "open", "slightly_open"]

# Class-level sprite cache: {(character_name, size): {mouth_state: PIL.Image}}
_sprite_cache: Dict[Tuple[str, int], Dict[str, Image.Image]] = {}


def _load_config() -> dict:
    """Load character configuration from config.yaml."""
    if os.path.exists(CONFIG_PATH):
        with open(CONFIG_PATH, "r") as f:
            return yaml.safe_load(f) or {}
    return {}


class CharacterRenderer:
    """Renders an animated character with lip-sync mouth movement.

    Sprites are full character images (one per mouth state) generated by
    DALL-E 3.  Each image IS the complete character with that mouth
    position — no cropping or overlay compositing needed.
    """

    # Oscillation frequency for jaw movement (cycles per second)
    OSCILLATION_HZ = 8.0

    # Anticipation: mouth starts opening slightly before word audio
    ANTICIPATION_SEC = 0.05

    # Breathing animation
    BREATHING_HZ = 0.4
    BREATHING_AMPLITUDE = 3  # pixels

    def __init__(
        self,
        character_name: str = "turtle",
        position_x: int = 50,
        position_y: int = 1500,
        size: int = 280,
        opacity: float = 0.92,
    ):
        self.character_name = character_name
        self.position_x = position_x
        self.position_y = position_y
        self.size = size
        self.opacity = opacity

        # Load sprites (uses class-level cache)
        self.sprites = self._load_sprites()
        self.available = len(self.sprites) > 0

        if self.available:
            logger.info(
                "Character '%s' loaded: %d mouth states, size=%dpx",
                character_name,
                len(self.sprites),
                size,
            )
        else:
            logger.warning(
                "Character '%s' has no sprites — rendering disabled",
                character_name,
            )

    def _load_sprites(self) -> Dict[str, Image.Image]:
        """Load and resize character sprites, using class-level cache."""
        cache_key = (self.character_name, self.size)
        if cache_key in _sprite_cache:
            return _sprite_cache[cache_key]

        sprites_dir = os.path.join(
            PROJECT_ROOT, "assets", "characters", self.character_name
        )

        if not os.path.isdir(sprites_dir):
            logger.debug("Sprites directory not found: %s", sprites_dir)
            _sprite_cache[cache_key] = {}
            return {}

        # Expected filenames for each mouth state
        mouth_files = {
            "closed": "mouth_closed.png",
            "slightly_open": "mouth_slightly_open.png",
            "open": "mouth_open.png",
            "wide": "mouth_wide.png",
        }

        loaded: Dict[str, Image.Image] = {}

        for state, filename in mouth_files.items():
            path = os.path.join(sprites_dir, filename)
            if not os.path.isfile(path):
                logger.debug("Missing sprite: %s", path)
                continue

            try:
                img = Image.open(path).convert("RGBA")

                # Remove white/light background — make it transparent
                img = self._remove_background(img)

                # Resize preserving aspect ratio, fitting within size x size
                orig_w, orig_h = img.size
                scale = self.size / max(orig_w, orig_h)
                new_w = int(orig_w * scale)
                new_h = int(orig_h * scale)
                img = img.resize((new_w, new_h), Image.LANCZOS)

                loaded[state] = img
            except Exception as e:
                logger.warning("Failed to load sprite %s: %s", path, e)

        _sprite_cache[cache_key] = loaded
        return loaded

    @staticmethod
    def _remove_background(img: Image.Image, threshold: int = 230) -> Image.Image:
        """Remove white/light background by making light pixels transparent.

        Uses a simple luminance threshold — pixels above the threshold
        become fully transparent.  A smooth feather edge is applied so
        the character blends naturally onto the video frame.
        """
        import numpy as np

        data = np.array(img, dtype=np.float32)  # (H, W, 4)
        r, g, b, a = data[:, :, 0], data[:, :, 1], data[:, :, 2], data[:, :, 3]

        # Luminance of each pixel
        luminance = 0.299 * r + 0.587 * g + 0.114 * b

        # Pixels brighter than threshold → transparent
        # Smooth feather between threshold-30 and threshold
        feather_start = threshold - 30
        mask = np.ones_like(luminance)  # 1 = keep
        mask[luminance > threshold] = 0.0
        feather_zone = (luminance > feather_start) & (luminance <= threshold)
        mask[feather_zone] = 1.0 - (luminance[feather_zone] - feather_start) / (threshold - feather_start)

        # Apply mask to existing alpha channel
        data[:, :, 3] = a * mask

        return Image.fromarray(data.astype(np.uint8), "RGBA")

    def _get_mouth_state(
        self, t: float, word_timestamps: List[Dict]
    ) -> str:
        """Determine which mouth image to use at time t.

        Args:
            t: Current time in seconds.
            word_timestamps: List of dicts with 'start' and 'end' keys
                             (word-level timing from Whisper).

        Returns:
            Mouth state name: 'closed', 'slightly_open', 'open', or 'wide'.
        """
        if not word_timestamps:
            return "closed"

        # Check if t falls within any word (with anticipation)
        active_word = None
        for word in word_timestamps:
            w_start = word.get("start", 0)
            w_end = word.get("end", 0)

            # Include anticipation window before the word
            anticipated_start = w_start - self.ANTICIPATION_SEC

            if anticipated_start <= t <= w_end:
                active_word = word
                break

        if active_word is None:
            return "closed"

        # Oscillate through mouth states using sine wave
        w_start = active_word["start"]
        elapsed = t - (w_start - self.ANTICIPATION_SEC)

        # Sine oscillation: 0→1→0→-1→0 mapped to mouth state indices
        # MOUTH_STATES = [closed, slightly_open, open, wide, open, slightly_open]
        phase = math.sin(2 * math.pi * self.OSCILLATION_HZ * elapsed)

        # Map sine output (-1..1) to index (0..len-1)
        normalized = (phase + 1) / 2  # 0..1
        index = int(normalized * (len(MOUTH_STATES) - 1))
        index = min(index, len(MOUTH_STATES) - 1)

        state = MOUTH_STATES[index]

        # Fall back to closest available state if this one wasn't loaded
        if state not in self.sprites:
            # Try fallback order
            for fallback in ["closed", "slightly_open", "open", "wide"]:
                if fallback in self.sprites:
                    return fallback
            return "closed"

        return state

    def render(
        self,
        frame: Image.Image,
        t: float,
        word_timestamps: Optional[List[Dict]] = None,
    ) -> Image.Image:
        """Paste the character onto frame with lip-sync and breathing.

        Args:
            frame: RGBA PIL Image to render onto (modified in place).
            t: Current time in seconds.
            word_timestamps: Word-level timestamps for lip sync.
                             If None, mouth stays closed.

        Returns:
            The frame (same object, modified in place).
        """
        if not self.available:
            return frame

        # Determine mouth state
        mouth_state = self._get_mouth_state(t, word_timestamps or [])

        sprite = self.sprites.get(mouth_state)
        if sprite is None:
            # Last resort: use any available sprite
            if self.sprites:
                sprite = next(iter(self.sprites.values()))
            else:
                return frame

        # Breathing animation: subtle vertical oscillation
        breathing_offset = int(
            self.BREATHING_AMPLITUDE
            * math.sin(2 * math.pi * self.BREATHING_HZ * t)
        )

        paste_x = self.position_x
        paste_y = self.position_y + breathing_offset

        # Apply opacity by modifying the alpha channel of a copy
        if self.opacity < 1.0:
            sprite_copy = sprite.copy()
            # Scale the existing alpha channel
            r, g, b, a = sprite_copy.split()
            a = a.point(lambda x: int(x * self.opacity))
            sprite_copy = Image.merge("RGBA", (r, g, b, a))
        else:
            sprite_copy = sprite

        # Paste with alpha mask for transparency
        # Ensure paste coordinates are within frame bounds
        frame_w, frame_h = frame.size
        sprite_w, sprite_h = sprite_copy.size

        # Clamp position to keep at least part of the sprite visible
        if paste_x + sprite_w <= 0 or paste_x >= frame_w:
            return frame
        if paste_y + sprite_h <= 0 or paste_y >= frame_h:
            return frame

        frame.paste(sprite_copy, (paste_x, paste_y), sprite_copy)

        return frame


# ── Module-level singleton ───────────────────────────────────────

_renderer: Optional[CharacterRenderer] = None


def get_character_renderer() -> Optional[CharacterRenderer]:
    """Get or create the character renderer singleton.

    Returns None if the character system is disabled in config or if
    sprite assets are missing.
    """
    global _renderer

    if _renderer is not None:
        return _renderer if _renderer.available else None

    config = _load_config()
    char_config = config.get("character", {})

    if not char_config.get("enabled", False):
        logger.debug("Character renderer disabled in config")
        return None

    _renderer = CharacterRenderer(
        character_name=char_config.get("name", "turtle"),
        position_x=char_config.get("position_x", 50),
        position_y=char_config.get("position_y", 1500),
        size=char_config.get("size", 280),
        opacity=char_config.get("opacity", 0.92),
    )

    if not _renderer.available:
        logger.info("Character renderer created but no sprites found — disabled")
        return None

    return _renderer
