"""Append-only ledger of what was published, where, and under what text.

WHY THIS EXISTS. `manager.upload()` returns an `UploadResult` carrying
`upload_id` and `url`, and both call sites in admin.py threw them away. The
only trace of a publication was a `title` string written into the artifact's
sidecar — and it was the PRE-adaptation title, missing the `#Shorts` suffix
that `adapt_for_platform` adds, so it did not even match what was live.
Nothing in this repo could name a published video.

WHY A SEPARATE LEDGER RATHER THAN THE ARTIFACT SIDECAR.

A publication is an EVENT, not a property of a file. Three requirements decide
the shape, and the sidecar fails two of them:

  survives re-render   The sidecar is regenerated by the pipeline and MOVED by
                       move_to_uploaded. Re-render the same topic and the
                       upload record is gone, while the video stays live on
                       YouTube forever. A ledger outside the artifact tree
                       cannot be clobbered by a render.

  many platforms       The same artifact can go to YouTube, TikTok and
                       Instagram, each with its own id, url and — after
                       adapt_for_platform — its own title and description.
                       That is one row per publication, not one field per
                       artifact.

  append-only          A publication cannot be un-happened. Rewriting a JSON
                       blob invites a partial write to lose history; appending
                       a line cannot.

JSONL, one event per line, at output/published/ledger.jsonl.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
LEDGER_DIR = ROOT / "output" / "published"
LEDGER_PATH = LEDGER_DIR / "ledger.jsonl"

#: Attempts live in their OWN file, not as status rows in the ledger.
#:
#: The append-only reasoning in the module docstring applies to both — an
#: attempt is an event that cannot be un-happened either, so it gets the same
#: append + fsync discipline. What does NOT carry over is the namespace.
#:
#: Every existing reader of the ledger means "this was published" by a row's
#: existence. `unrecorded_platforms` is exactly that: a platform is recorded
#: if a row names it. Putting attempt rows in the same file would silently
#: change what that function returns — a platform with an open attempt and no
#: publication would report as already recorded, and the guard would skip a
#: video that was never published. Its existing tests would still pass,
#: because they know nothing about attempts.
#:
#: The two files also have different lifecycles. A publication is an answer
#: and never changes. An attempt is a QUESTION — "did this land?" — that gets
#: resolved later by a second row. Keeping questions out of the answer log is
#: what lets the answer log stay a set of facts.
ATTEMPTS_PATH = LEDGER_DIR / "attempts.jsonl"

SCHEMA_VERSION = 1

#: Attempt lifecycle. Append-only: the latest row for an (artifact, platform)
#: pair wins, earlier rows stay as history.
ATTEMPT_STARTED = "started"      # about to upload; no bytes sent yet
ATTEMPT_SESSION = "session"      # a resumable session URI exists
ATTEMPT_PUBLISHED = "published"  # confirmed live, ledger row written
ATTEMPT_FAILED = "failed"        # confirmed NOT live; safe to retry
ATTEMPT_UNKNOWN = "unknown"      # could not be determined; needs a human


#: The real files, captured at import before any test can monkeypatch them.
_REAL_LEDGER = LEDGER_PATH
_REAL_ATTEMPTS = ATTEMPTS_PATH


def _refuse_real_path(path: Path) -> None:
    """Under pytest, refuse to write to the real ledger or attempt log.

    A test once wrote 13 fixture rows into the real attempts file. The ledger
    is append-only and records irreversible events, so a poisoned row cannot
    be rewritten away — only appended around. Same category as .tokens/: no
    recovery story, so the protection has to be structural rather than
    remembered.

    tests/conftest.py redirects both paths for every test, which handles the
    common case. This covers what a fixture cannot: a test that re-imports
    this module, patches the globals back, computes a path itself, or spawns
    a subprocess that inherits PYTEST_CURRENT_TEST.

    Deliberately keyed on the RESOLVED path, not on the module global, so
    reassigning LEDGER_PATH to the same file is still caught.
    """
    if "PYTEST_CURRENT_TEST" not in os.environ:
        return
    try:
        resolved = Path(path).resolve()
    except OSError:
        return
    for real, name in ((_REAL_LEDGER, "the publication ledger"),
                       (_REAL_ATTEMPTS, "the attempt log")):
        if resolved == Path(real).resolve():
            raise PublicationRecordError(
                f"REFUSING to write to {name} ({resolved}) from a test. "
                f"It is append-only and records irreversible events, so a "
                f"fixture row cannot be removed afterwards. Use the "
                f"ledger_path/attempts_path argument or the autouse fixture "
                f"in tests/conftest.py."
            )


class PublicationRecordError(RuntimeError):
    """Raised when a publication happened but could not be recorded.

    This is deliberately loud. The video is live and we cannot name it, which
    is strictly worse than a failed upload — a failed upload can be retried,
    an unrecorded one has to be found by hand.
    """


def record_publication(
    *,
    artifact: str,
    video_path: str,
    platform: str,
    upload_id: Optional[str],
    url: Optional[str],
    published_title: str,
    published_description: str,
    hashtags: Optional[List[str]] = None,
    video_type: str = "",
    extra: Optional[Dict] = None,
    ledger_path: Optional[Path] = None,
) -> Dict:
    """Append one publication event. Returns the row written.

    `published_title` / `published_description` MUST be the post-adaptation
    strings actually handed to the platform API — the `#Shorts` suffix
    included. Recording the pre-adaptation text is what made the previous
    record unjoinable to the live video.

    Raises PublicationRecordError if the row cannot be persisted.
    """
    path = Path(ledger_path) if ledger_path else LEDGER_PATH
    _refuse_real_path(path)

    row = {
        "schema": SCHEMA_VERSION,
        "artifact": artifact,
        "video_path": str(video_path),
        "video_type": video_type,
        "platform": platform,
        "upload_id": upload_id,
        "url": url,
        "published_at": datetime.now().isoformat(),
        "published_title": published_title,
        "published_description": published_description,
        "hashtags": list(hashtags or []),
    }
    if extra:
        row["extra"] = extra

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        line = json.dumps(row, ensure_ascii=False)
        # Append and fsync: a publication that is live but unrecorded is the
        # failure this module exists to prevent, so the write is not left
        # sitting in a buffer that a crash would discard.
        with open(path, "a", encoding="utf-8") as fh:
            fh.write(line + "\n")
            fh.flush()
            os.fsync(fh.fileno())
    except Exception as exc:                        # noqa: BLE001
        raise PublicationRecordError(
            f"{platform} upload succeeded (id={upload_id!r}) but the record "
            f"could not be written to {path}: {exc}"
        ) from exc

    logger.info("recorded publication: %s -> %s id=%s", artifact, platform, upload_id)
    return row


def record_upload_result(*, artifact: str, video_path: str, video_type: str,
                         platform: str, result, sent_title: str,
                         sent_description: str, sent_hashtags: List[str],
                         ledger_path: Optional[Path] = None) -> Dict:
    """Record a publication from an uploader `result`, whatever shape it is.

    THE ONLY RECORDER. It lives here rather than in admin.py because admin.py
    imports streamlit at module scope, and the headless path in main.py — the
    one unattended publishing will run — cannot pay that import or the
    dashboard-level side effects (basicConfig, load_dotenv) that come with it.
    A second recorder in main.py was the alternative, and two recorders drift.

    The result shape is normalised HERE for the same reason. `manager.upload()`
    returns an UploadResult from some backends and a plain dict from others,
    and every caller that unpacks it by hand is a place the id can be dropped
    silently — which is exactly how the ids were lost before the ledger
    existed.

    Raises PublicationRecordError. Callers must handle it: the upload has
    already happened and cannot be undone, so a failure here means a video is
    live that this repo cannot name. That is louder-than-usual by design.
    """
    upload_id = (result.get("upload_id") if isinstance(result, dict)
                 else getattr(result, "upload_id", None))
    url = (result.get("url") if isinstance(result, dict)
           else getattr(result, "url", None))

    return record_publication(
        artifact=artifact,
        video_path=video_path,
        video_type=video_type,
        platform=platform,
        upload_id=upload_id,
        url=url,
        published_title=sent_title,
        published_description=sent_description,
        hashtags=sent_hashtags,
        ledger_path=ledger_path,
    )


def read_ledger(ledger_path: Optional[Path] = None) -> List[Dict]:
    """Every recorded publication, oldest first. Bad lines are skipped loudly."""
    path = Path(ledger_path) if ledger_path else LEDGER_PATH
    if not path.exists():
        return []
    rows = []
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = line.strip()
        if not line:
            continue
        try:
            rows.append(json.loads(line))
        except ValueError:
            logger.error("ledger line %d is not valid JSON; skipping", n)
    return rows


def find_by_artifact(artifact: str, ledger_path: Optional[Path] = None) -> List[Dict]:
    """Every platform this artifact was published to."""
    return [r for r in read_ledger(ledger_path) if r.get("artifact") == artifact]


def find_by_upload_id(upload_id: str, ledger_path: Optional[Path] = None) -> Optional[Dict]:
    for r in read_ledger(ledger_path):
        if r.get("upload_id") == upload_id:
            return r
    return None


def record_attempt(*, artifact: str, platform: str, status: str,
                   video_path: str = "", session_uri: Optional[str] = None,
                   upload_id: Optional[str] = None,
                   file_size: Optional[int] = None,
                   detail: str = "", attempts_path: Optional[Path] = None) -> Dict:
    """Append one attempt event. Returns the row written.

    Written BEFORE any bytes are uploaded. That is the whole point: between
    `manager.upload()` returning a live video and `record_publication()`
    running, nothing on disk said an upload was in flight, so a retry could
    not tell "already published" from "never uploaded". hPdSoqjvu3E and
    IvO969ZeQsM are that window — the same video, three minutes apart.

    `session_uri` is the reconciliation handle. Querying it answers the
    question definitively: Google returns 201 with the video resource if the
    upload already completed, 308 if it did not. Every failure path in
    uploader.py used to discard it.

    Unlike record_publication this does NOT raise on failure. An attempt that
    cannot be written is a reason to refuse the upload, not to crash after it
    — the caller checks the return value.
    """
    path = Path(attempts_path) if attempts_path else ATTEMPTS_PATH
    _refuse_real_path(path)

    row = {
        "schema": SCHEMA_VERSION,
        "artifact": artifact,
        "platform": platform,
        "status": status,
        "video_path": str(video_path),
        "session_uri": session_uri,
        "upload_id": upload_id,
        "file_size": file_size,
        "detail": detail,
        "at": datetime.now().isoformat(),
    }

    path.parent.mkdir(parents=True, exist_ok=True)
    line = json.dumps(row, ensure_ascii=False)
    with open(path, "a", encoding="utf-8") as fh:
        fh.write(line + "\n")
        fh.flush()
        os.fsync(fh.fileno())

    logger.info("attempt %s: %s -> %s", status, artifact, platform)
    return row


def read_attempts(attempts_path: Optional[Path] = None) -> List[Dict]:
    """Every attempt event, oldest first. Bad lines are skipped loudly."""
    path = Path(attempts_path) if attempts_path else ATTEMPTS_PATH
    if not path.exists():
        return []
    rows = []
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError:
            logger.error("attempts.jsonl:%d is not valid JSON; skipping", n)
    return rows


def latest_attempt(artifact: str, platform: str,
                   attempts_path: Optional[Path] = None) -> Optional[Dict]:
    """The most recent attempt row for this artifact+platform, or None.

    Append-only means the state of an attempt is its LAST row, not its first.
    A `started` row followed by a `failed` row is a closed attempt.
    """
    match = [r for r in read_attempts(attempts_path)
             if r.get("artifact") == artifact and r.get("platform") == platform]
    return match[-1] if match else None


def open_attempt(artifact: str, platform: str,
                 attempts_path: Optional[Path] = None) -> Optional[Dict]:
    """An attempt that started and never reached a terminal state.

    This is the dangerous state and the reason the guard cannot be
    `unrecorded_platforms` alone: no publication row exists, so the ledger
    says "never published", while the video may well be live.
    """
    row = latest_attempt(artifact, platform, attempts_path)
    if row and row.get("status") in (ATTEMPT_STARTED, ATTEMPT_SESSION,
                                     ATTEMPT_UNKNOWN):
        return row
    return None


def unrecorded_platforms(artifact: str, platforms: List[str],
                         ledger_path: Optional[Path] = None) -> List[str]:
    """Platforms in `platforms` with no ledger row for this artifact."""
    seen = {r.get("platform") for r in find_by_artifact(artifact, ledger_path)}
    return [p for p in platforms if p not in seen]
